### ISSUE TITLE
Support No Internet Connection State

### ISSUE THREAD

**Issue by Spikeysanju** [TheCodeMonks/NYTimes-App#12] opened 2020-10-01 03:00 UTC
### Proposed Change

- Support for No Internet Connection & Connection Back with animation  using  **_`StateFlow`_** 
- This change is to encourage the participants of **_`Hacktoberfest`_** for the this events

### Expected Behaviour

`⚠️ Note - Fade in & fade out collapse needs to be done!`

![NO INTERNET CONENCTION](https://user-images.githubusercontent.com/23400022/94985978-832e5c00-0578-11eb-99cb-5af7fbfcc062.png)
![NO INTERNET CONENCTION-1](https://user-images.githubusercontent.com/23400022/94985980-845f8900-0578-11eb-87df-de2a233f8625.png)

### Reference

**_`StateFlow`_** -  https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/

**Comment by ch8n** [comment] 2020-10-03 07:11
Hi @Spikeysanju I will like to work on this

**Comment by Spikeysanju** [comment] 2020-10-03 07:35
Hello @ch8n , Thanks for your interest. I have updated the issue with expected behaviour of Internet connection state. Kindly take a look at it & let me know.

**Comment by ch8n** [comment] 2020-10-03 07:54
> Hello @ch8n , Thanks for your interest. I have updated the issue with expected behaviour of Internet connection state. Kindly take a look at it & let me know.

Hi @Spikeysanju thanks for the quick response, please assign it to me I will get started, 

just to be on the same page for requirements and intended behaviour please answer the following:
1. No internet strip view, comes when the app goes offline?
2. When the user is offline, will the red strip stay visible until the user is online or will be gone after some time?
3.  When the app comes online it turns green?
5. after how much time delay would it be gone after the user is online?
6. fade in / fade out animation will be used for switching between red and green mode?
7. collapse animation will play on appearing and disappearing of the view?

**Comment by Spikeysanju** [comment] 2020-10-03 08:08
@ch8n  Answer for you questions

1. Yes, `if no internet the view will be displayed`
2.  Yes, `It will stay until user comes to online`
3. Yes, when user comes online back, `"No internet connection view " will turn into "you're online" with fade in/out animation`
4. We can make time delay for `3 seconds`
5. Yes, `we have to add fade in/out animation for color switch "red -> green" or "green -> red"`
6. Yes,  `We have to animate the view for appearing & disappearing `

You can take some references from. Try turning on & off Internet connection, you will get some idea about it [Foodium app](https://github.com/PatilShreyas/Foodium)

Feel free to contact me if you have any queries, Thanks you!

**Closed** 2020-10-04 13:22 UTC
Labels: Hacktoberfest
